[General]
backgroundColor=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
currentVersion=1.103.0
layerDock=false
moleculeDock=false
recentFiles=/mnt/Data/Avogadro2/Imports/nylon-66.sdf, /mnt/Data/Avogadro2/Exports/DecylDecylDecylDecane.cjson, /mnt/Data/Avogadro2/Imports/sodium-triphosphate.sdf, /mnt/Data/Avogadro2/Imports/glucose.sdf, /mnt/Data/Avogadro2/Imports/fructose.sdf, /mnt/Data/Avogadro2/Imports/alcohol.sdf, /mnt/Data/Avogadro2/Imports/sodium-chloride.sdf, /mnt/Data/Avogadro2/Imports/sodium-bicarbonate.sdf, /mnt/Data/Avogadro2/Imports/ammonium-nitrate.sdf, /mnt/Data/Avogadro2/Imports/benzene.sdf
sceneDock=false
toolDock=false
viewDock=false

[MainWindow]
BallStick=true
Cartoons=true
CloseContacts=true
CrystalScene=false
Dipole=true
Force=true
Label=true
Licorice=false
NonCovalent=true
OverlayAxes=true
QTAIMScenePlugin=true
SurfaceRender=true
SymmetryScene=true
VanDerWaals=false
Wireframe=false
ao_enabled=true
ao_strength=1
dof_enabled=true
ed_enabled=true
fog_enabled=true
lastOpenDir=/mnt/Data/Avogadro2/Imports
lastSaveDir=/mnt/Data/Avogadro2/Exports
perspective=true
pos=@Point(1930 59)
size=@Size(1258 1009)

[autoopt]
method=MMFF94

[ballandstick]
atomScale=0.30000001192092896
bondRadius=0.10000000149011612
opacity=1

[cartoon]
backbone=true
ribbon=true
rope=true
simpleCartoon=true
trace=true
tube=true

[editortool]
userElements=2, 38, 39

[interpreters]
condaEnvironment=avogadro
condaPath=/home/sudar/.conda/miniconda3/condabin/conda
python=/home/sudar/.conda/miniconda3/envs/avogadro/bin/python

[label]
atomoptions=2

[navigator]
zoom=-1

[overlayAxes]
enabled=true

[templatetool]
ligandType=0
